# Generated by Django 4.1 on 2024-12-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Musician",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=63)),
                ("last_name", models.CharField(max_length=63)),
                ("instrument", models.CharField(max_length=63)),
                ("age", models.IntegerField()),
                ("date_of_applying", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="musician",
            constraint=models.CheckConstraint(
                check=models.Q(("age__gte", 14)), name="acceptable_age"
            ),
        ),
    ]
